apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 4
      activeDeadlineSeconds: 20
      completions: 2
      parallelism: 2
      template:
        spec:
          containers:
          - name: test-cronjob
            image: busybox:stable
            command:
            - echo
            - This is a test cronjob!!
          restartPolicy: Never

