apiVersion: v1
kind: Pod
metadata: 
  name: saim-pdo
  namespace: alpha-namespace

spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "1Gi"
        cpu: "1"
      limits:
        memory: "1.5Gi"
        cpu: "1"
