apiVersion: v1
kind: Pod
metadata: 
  name: test-pod
  namespace: default
  labels:
    name: blue

spec:
  containers:
  - name: nginx
    image: kodekloud/webapp-conntest
    env:
    - name: APP_NAME
      value: Blue - Marketing Application
    - name: BG_COLOR
      value: blue
    ports:
    - containerPort: 8080
      protocol: TCP
