apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: ubuntu-container
    image: ubuntu
    command:
    - 'sleep'
    - '3600'
    resources:
      limits:
        cpu: 2
      requests:
        cpu: 1
