apiVersion: v1
kind: Pod
metadata: 
  name: test-pod-4
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: ubuntu-container
    image: ubuntu
    command: ['sleep','5000']
    securityContext:
      runAsUser: 1002
  - name: ubuntu-sidecar
    image: ubuntu
    command:
    - "sleep"
    - "4800"
