apiVersion: v1
kind: Pod
metadata:
  name: ambassador-test-pod
spec:
  containers:
  - name: main-container
    image: curlimages/curl:latest
    command: ['sh', '-c', 'while true; do curl localhost:8080; sleep 5; done']

  - name: ambassador-container
    image: haproxy:2.4
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: config
      mountPath: /usr/local/etc/haproxy
  volumes:
  - name: config
    configMap:
      name: haproxy-config

