apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    app: frontend
    type: development

spec:
  selector:
    app: frontend
  template:
    metadata:
      name: my-pod
      labels:
        app: frontend
    spec:
      containers:
      - name: alpha
        image: nginx
  replicas: 3
