apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: frontend-rs
    tier: development

spec:
  replicas: 5
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: my-rs
      labels:
        app: myapp
    spec:
      containers:
      - name: alpha
        image: nginx

