apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myapp-deployment
  labels:
    app: myapp
    tier: frontend
 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      name: nginx-2
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
