apiVersion: v1
kind: Pod
metadata: 
  name: sidecar-practice-pod

spec:
  containers:
  - name: main-container
    image: busybox:stable
    command: ['sh', '-c', 'echo "i am learning kubernertes" > /output/data.txt; while true; do sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /output

  - name: sidecar-container
    image: busybox:stable
    command: ['sh', '-c', 'while true; do cat /input-dir/data.txt; sleep 5; done']
    volumeMounts:
    - name: shared-volume
      mountPath: /input-dir
  volumes:
  - name: shared-volume
    emptyDir: {}
