apiVersion: v1
kind: Service
metadata:
  labels:
    run: test
  name: test-service
spec:
  ports:
    - nodePort: 32411  # Ensure it's within 30000-32767
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: test
  type: NodePort

