apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-prod
  labels:
    app: simple-webapp

spec:
  containers:
  - name: production-webapp
    image: kodekloud/webapp-delayed-start
    ports:
    - containerPort: 8080
      protocol: TCP 
    env:
    - name: APP_START_DELAY
      value: "80"
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
    livenessProbe:
      httpGet:
        path: /live
        port: 8080
      periodSeconds: 3
      initialDelaySeconds: 100  
