apiVersion: v1
kind: Pod
metadata: 
  name: web-pod
  namespace: default
  labels:
    app: color

spec:
  containers:
  - name: test-container
    image: kodekloud/webapp-color
    envFrom:
    - configMapRef:
        name: web-config

