apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: saim-deployment
  name: saim-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saim-deployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saim-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: platform
                operator: Exists 
