apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    env: dev
    tier: frontend 
  name: alnafi
spec:
  containers:
  - image: nginx
    name: alnafi
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
