apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mosquito
  name: mosquito
spec:
  containers:
  - image: nginx
    name: bee
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
